<a href="https://colab.research.google.com/github/sumanamishra1120-ux/Chance-of-Admission-Higher-Studies/blob/main/Chance_of_Admission_Higher_Studies.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chance of Admission for Higher Studies

## Data Analysis and Machine Learning Project

## Project Objective

The objective of this project is to analyze different factors that may be associated with a student's chance of admission to higher studies.

The project uses student information such as GRE Score, TOEFL Score, University Rating, Statement of Purpose, Letter of Recommendation, Undergraduate CGPA, and Research Experience.

Machine learning techniques will be used to estimate the Chance of Admit based on these features.

## Dataset Features

The dataset contains the following features:

1. GRE Score - GRE examination score
2. TOEFL Score - TOEFL examination score
3. University Rating - Rating of the university
4. SOP - Statement of Purpose strength
5. LOR - Letter of Recommendation strength
6. CGPA - Undergraduate CGPA
7. Research - Research experience
8. Chance of Admit - Estimated chance of admission

## Feature Ranges

- GRE Score: 290 to 340
- TOEFL Score: 92 to 120
- University Rating: 1 to 5
- SOP: 1 to 5
- LOR: 1 to 5
- Undergraduate CGPA: 6.8 to 9.92
- Research Experience: 0 or 1
- Chance of Admit: approximately 0.34 to 0.97

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import sys

print("Python Version:", sys.version)

Python Version: 3.13.15 (main, Aug  6 2026, 11:06:22) [GCC 13.3.0]

In [3]:
print("Pandas Version:", pd.__version__)
print("NumPy Version:", np.__version__)
print("Matplotlib Version:", plt.matplotlib.__version__)
print("Seaborn Version:", sns.__version__)

Pandas Version: 2.2.3
NumPy Version: 2.1.3
Matplotlib Version: 3.10.0
Seaborn Version: 0.13.2

## Project Workflow

The project will be completed in the following stages:

1. Project Setup
2. Data Collection
3. Data Understanding
4. Data Cleaning
5. Exploratory Data Analysis
6. Data Visualization
7. Correlation Analysis
8. Feature Selection
9. Data Splitting
10. Machine Learning Model Building
11. Model Evaluation
12. Model Comparison
13. Admission Prediction
14. Final Documentation

## Technologies Used

- Python
- Google Colab
- Pandas
- NumPy
- Matplotlib
- Seaborn
- Scikit-learn
- GitHub

# Day 2 - Loading the Dataset

In [4]:
import pandas as pd

url = "https://raw.githubusercontent.com/GnanaKeerthana/Admission_Prediction/main/Admission_Predict.csv"

df = pd.read_csv(url)

print("Dataset loaded successfully!")

Dataset loaded successfully!

In [5]:
df.head()

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,324,107,4,4.0,4.5,8.87,1,0.76
2,3,316,104,3,3.0,3.5,8.00,1,0.72
3,4,322,110,3,3.5,2.5,8.67,1,0.80
4,5,314,103,2,2.0,3.0,8.21,0,0.65

In [6]:
df.tail()

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
395,396,324,110,3,3.5,3.5,9.04,1,0.82
396,397,325,107,3,3.0,3.5,9.11,1,0.84
397,398,330,116,4,5.0,4.5,9.45,1,0.91
398,399,312,103,3,3.5,4.0,8.78,0,0.67
399,400,333,117,4,5.0,4.0,9.66,1,0.95

In [7]:
df.shape

(400, 9)

In [8]:
df.columns

Index(['Serial No.', 'GRE Score', 'TOEFL Score', 'University Rating', 'SOP',
       'LOR ', 'CGPA', 'Research', 'Chance of Admit '],
      dtype='object')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Serial No.         400 non-null    int64
 1   GRE Score          400 non-null    int64
 2   TOEFL Score        400 non-null    int64
 3   University Rating  400 non-null    int64
 4   SOP                400 non-null    float64
 5   LOR                400 non-null    float64
 6   CGPA               400 non-null    float64
 7   Research           400 non-null    int64
 8   Chance of Admit    400 non-null    float64
dtypes: float64(4), int64(5)
memory usage: 28.3 KB

In [10]:
df.describe()

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
count,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000
mean,200.500000,316.807500,107.410000,3.087500,3.400000,3.452500,8.598925,0.547500,0.724350
std,115.614301,11.473646,6.069514,1.143728,1.006869,0.898478,0.596317,0.498362,0.142609
min,1.000000,290.000000,92.000000,1.000000,1.000000,1.000000,6.800000,0.000000,0.340000
25%,100.750000,308.000000,103.000000,2.000000,2.500000,3.000000,8.170000,0.000000,0.640000
50%,200.500000,317.000000,107.000000,3.000000,3.500000,3.500000,8.610000,1.000000,0.730000
75%,300.250000,325.000000,112.000000,4.000000,4.000000,4.000000,9.062500,1.000000,0.830000
max,400.000000,340.000000,120.000000,5.000000,5.000000,5.000000,9.920000,1.000000,0.970000

### Day 2 Conclusion

The dataset has been successfully loaded into the Python environment.
We checked the first and last rows, dataset shape, column names,
data types, and basic statistical information.

# Day 3 – Understanding the Dataset

In [11]:
df.columns

Index(['Serial No.', 'GRE Score', 'TOEFL Score', 'University Rating', 'SOP',
       'LOR ', 'CGPA', 'Research', 'Chance of Admit '],
      dtype='object')

In [12]:
df.shape

(400, 9)

In [13]:
df.dtypes

Serial No.             int64
GRE Score              int64
TOEFL Score            int64
University Rating      int64
SOP                  float64
LOR                  float64
CGPA                 float64
Research               int64
Chance of Admit      float64
dtype: object

In [14]:
df.isnull().sum()

Serial No.           0
GRE Score            0
TOEFL Score          0
University Rating    0
SOP                  0
LOR                  0
CGPA                 0
Research             0
Chance of Admit      0
dtype: int64

In [15]:
df.duplicated().sum()

np.int64(0)

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Serial No.         400 non-null    int64
 1   GRE Score          400 non-null    int64
 2   TOEFL Score        400 non-null    int64
 3   University Rating  400 non-null    int64
 4   SOP                400 non-null    float64
 5   LOR                400 non-null    float64
 6   CGPA               400 non-null    float64
 7   Research           400 non-null    int64
 8   Chance of Admit    400 non-null    float64
dtypes: float64(4), int64(5)
memory usage: 28.3 KB

In [17]:
df.describe()

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
count,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000
mean,200.500000,316.807500,107.410000,3.087500,3.400000,3.452500,8.598925,0.547500,0.724350
std,115.614301,11.473646,6.069514,1.143728,1.006869,0.898478,0.596317,0.498362,0.142609
min,1.000000,290.000000,92.000000,1.000000,1.000000,1.000000,6.800000,0.000000,0.340000
25%,100.750000,308.000000,103.000000,2.000000,2.500000,3.000000,8.170000,0.000000,0.640000
50%,200.500000,317.000000,107.000000,3.000000,3.500000,3.500000,8.610000,1.000000,0.730000
75%,300.250000,325.000000,112.000000,4.000000,4.000000,4.000000,9.062500,1.000000,0.830000
max,400.000000,340.000000,120.000000,5.000000,5.000000,5.000000,9.920000,1.000000,0.970000

In [18]:
df.head(10)

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,324,107,4,4.0,4.5,8.87,1,0.76
2,3,316,104,3,3.0,3.5,8.00,1,0.72
3,4,322,110,3,3.5,2.5,8.67,1,0.80
4,5,314,103,2,2.0,3.0,8.21,0,0.65
5,6,330,115,5,4.5,3.0,9.34,1,0.90
6,7,321,109,3,3.0,4.0,8.20,1,0.75
7,8,308,101,2,3.0,4.0,7.90,0,0.68
8,9,302,102,1,2.0,1.5,8.00,0,0.50
9,10,323,108,3,3.5,3.0,8.60,0,0.45

In [19]:
df.tail(10)

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
390,391,314,102,2,2.0,2.5,8.24,0,0.64
391,392,318,106,3,2.0,3.0,8.65,0,0.71
392,393,326,112,4,4.0,3.5,9.12,1,0.84
393,394,317,104,2,3.0,3.0,8.76,0,0.77
394,395,329,111,4,4.5,4.0,9.23,1,0.89
395,396,324,110,3,3.5,3.5,9.04,1,0.82
396,397,325,107,3,3.0,3.5,9.11,1,0.84
397,398,330,116,4,5.0,4.5,9.45,1,0.91
398,399,312,103,3,3.5,4.0,8.78,0,0.67
399,400,333,117,4,5.0,4.0,9.66,1,0.95

In [20]:
df["Research"].unique()

array([1, 0])

In [21]:
df["Research"].value_counts()

Research
1    219
0    181
Name: count, dtype: int64

## Day 3 Conclusion

Today, we understood the basic structure of the admission dataset.
We checked the column names, dataset size, data types, missing values,
duplicate rows, dataset information, and statistical summary.

We also checked the Research column and its values.

Day 4 – Rename and Clean Columns

In [22]:
import pandas as pd

url = "https://raw.githubusercontent.com/GnanaKeerthana/Admission_Prediction/main/Admission_Predict.csv"

df = pd.read_csv(url)

print("Dataset loaded successfully!")

Dataset loaded successfully!

In [23]:
print(df.columns)

Index(['Serial No.', 'GRE Score', 'TOEFL Score', 'University Rating', 'SOP',
       'LOR ', 'CGPA', 'Research', 'Chance of Admit '],
      dtype='object')

In [24]:
df.columns = df.columns.str.strip()

print(df.columns)

Index(['Serial No.', 'GRE Score', 'TOEFL Score', 'University Rating', 'SOP',
       'LOR', 'CGPA', 'Research', 'Chance of Admit'],
      dtype='object')

In [25]:
df.columns = [
    "serial_no",
    "gre_score",
    "toefl_score",
    "university_rating",
    "sop",
    "lor",
    "cgpa",
    "research",
    "chance_of_admit"
]

print("Columns renamed successfully!")

Columns renamed successfully!

In [26]:
print(df.columns.tolist())

['serial_no', 'gre_score', 'toefl_score', 'university_rating', 'sop', 'lor', 'cgpa', 'research', 'chance_of_admit']

In [27]:
print("Dataset shape:", df.shape)

Dataset shape: (400, 9)

In [28]:
df.head()

,serial_no,gre_score,toefl_score,university_rating,sop,lor,cgpa,research,chance_of_admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,324,107,4,4.0,4.5,8.87,1,0.76
2,3,316,104,3,3.0,3.5,8.00,1,0.72
3,4,322,110,3,3.5,2.5,8.67,1,0.80
4,5,314,103,2,2.0,3.0,8.21,0,0.65

In [29]:
print(df.isnull().sum())

serial_no            0
gre_score            0
toefl_score          0
university_rating    0
sop                  0
lor                  0
cgpa                 0
research             0
chance_of_admit      0
dtype: int64

In [30]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [31]:
print(df.dtypes)

serial_no              int64
gre_score              int64
toefl_score            int64
university_rating      int64
sop                  float64
lor                  float64
cgpa                 float64
research               int64
chance_of_admit      float64
dtype: object

In [32]:
df.describe()

,serial_no,gre_score,toefl_score,university_rating,sop,lor,cgpa,research,chance_of_admit
count,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000
mean,200.500000,316.807500,107.410000,3.087500,3.400000,3.452500,8.598925,0.547500,0.724350
std,115.614301,11.473646,6.069514,1.143728,1.006869,0.898478,0.596317,0.498362,0.142609
min,1.000000,290.000000,92.000000,1.000000,1.000000,1.000000,6.800000,0.000000,0.340000
25%,100.750000,308.000000,103.000000,2.000000,2.500000,3.000000,8.170000,0.000000,0.640000
50%,200.500000,317.000000,107.000000,3.000000,3.500000,3.500000,8.610000,1.000000,0.730000
75%,300.250000,325.000000,112.000000,4.000000,4.000000,4.000000,9.062500,1.000000,0.830000
max,400.000000,340.000000,120.000000,5.000000,5.000000,5.000000,9.920000,1.000000,0.970000

In [33]:
print("Day 4 completed successfully!")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])
print("Column names:")
print(df.columns.tolist())

Day 4 completed successfully!
Rows: 400
Columns: 9
Column names:
['serial_no', 'gre_score', 'toefl_score', 'university_rating', 'sop', 'lor', 'cgpa', 'research', 'chance_of_admit']

### Day 4 Conclusion

The dataset columns were cleaned and renamed using simple and meaningful names.
Extra spaces in column names were removed. The dataset contains 400 rows and 9 columns.
Missing values, duplicate rows, data types, and basic statistics were also checked.

Day 5 – Handling Missing Values

In [34]:
print(df.shape)

(400, 9)

In [35]:
print(df.isnull().sum())

serial_no            0
gre_score            0
toefl_score          0
university_rating    0
sop                  0
lor                  0
cgpa                 0
research             0
chance_of_admit      0
dtype: int64

In [36]:
total_missing = df.isnull().sum().sum()

print("Total missing values:", total_missing)

Total missing values: 0

In [37]:
print("Rows with missing values:", df.isnull().any(axis=1).sum())

Rows with missing values: 0

In [38]:
df[df.isnull().any(axis=1)]

Empty DataFrame
Columns: [serial_no, gre_score, toefl_score, university_rating, sop, lor, cgpa, research, chance_of_admit]
Index: []

In [39]:
missing_percentage = (df.isnull().sum() / len(df)) * 100

print(missing_percentage)

serial_no            0.0
gre_score            0.0
toefl_score          0.0
university_rating    0.0
sop                  0.0
lor                  0.0
cgpa                 0.0
research             0.0
chance_of_admit      0.0
dtype: float64

### Missing Value Handling

The dataset was checked for missing values.
There are no missing values in the dataset, so no rows or columns were removed and no values were filled.

In [40]:
print("Dataset shape after missing value check:", df.shape)

Dataset shape after missing value check: (400, 9)

In [41]:
print("Day 5 completed successfully!")
print("Total missing values:", df.isnull().sum().sum())
print("Dataset shape:", df.shape)

Day 5 completed successfully!
Total missing values: 0
Dataset shape: (400, 9)

### Day 5 Conclusion

The dataset was checked for missing values.
No missing values were found in any column.
Therefore, no missing-value treatment was required.
The dataset remains 400 rows and 9 columns.

## Day 6 - Check Duplicate Data

In [42]:
print("Total rows:", len(df))
print("Unique rows:", df.drop_duplicates().shape[0])

Total rows: 400
Unique rows: 400

In [43]:
duplicate_rows = df.duplicated().sum()

print("Number of duplicate rows:", duplicate_rows)

Number of duplicate rows: 0

In [44]:
df[df.duplicated()]

Empty DataFrame
Columns: [serial_no, gre_score, toefl_score, university_rating, sop, lor, cgpa, research, chance_of_admit]
Index: []

In [45]:
df = df.drop_duplicates()

print("Dataset shape after removing duplicates:", df.shape)

Dataset shape after removing duplicates: (400, 9)

In [46]:
print("Duplicate rows after cleaning:", df.duplicated().sum())

Duplicate rows after cleaning: 0

In [47]:
print("Day 6 completed successfully!")
print("Total rows:", len(df))
print("Duplicate rows:", df.duplicated().sum())
print("Dataset shape:", df.shape)

Day 6 completed successfully!
Total rows: 400
Duplicate rows: 0
Dataset shape: (400, 9)

## Day 6 Conclusion

The dataset was checked for duplicate rows.
No duplicate rows were found in the dataset.
The dataset contains 400 rows and 8 columns after cleaning.

## Day 7 - Range Validation

In [50]:
print("Dataset shape:", df.shape)

Dataset shape: (400, 9)

In [51]:
print("Current columns:")
print(df.columns.tolist())

Current columns:
['serial_no', 'gre_score', 'toefl_score', 'university_rating', 'sop', 'lor', 'cgpa', 'research', 'chance_of_admit']

In [52]:
print("Minimum values:")
print(df.min(numeric_only=True))

print("\nMaximum values:")
print(df.max(numeric_only=True))

Minimum values:
serial_no              1.00
gre_score            290.00
toefl_score           92.00
university_rating      1.00
sop                    1.00
lor                    1.00
cgpa                   6.80
research               0.00
chance_of_admit        0.34
dtype: float64

Maximum values:
serial_no            400.00
gre_score            340.00
toefl_score          120.00
university_rating      5.00
sop                    5.00
lor                    5.00
cgpa                   9.92
research               1.00
chance_of_admit        0.97
dtype: float64

In [53]:
print("GRE Score Range")
print("Minimum:", df["gre_score"].min())
print("Maximum:", df["gre_score"].max())

GRE Score Range
Minimum: 290
Maximum: 340

In [54]:
print("TOEFL Score Range")
print("Minimum:", df["toefl_score"].min())
print("Maximum:", df["toefl_score"].max())

TOEFL Score Range
Minimum: 92
Maximum: 120

In [55]:
print("University Rating Range")
print("Minimum:", df["university_rating"].min())
print("Maximum:", df["university_rating"].max())

University Rating Range
Minimum: 1
Maximum: 5

In [56]:
print("SOP Range")
print("Minimum:", df["sop"].min())
print("Maximum:", df["sop"].max())

SOP Range
Minimum: 1.0
Maximum: 5.0

In [57]:
print("LOR Range")
print("Minimum:", df["lor"].min())
print("Maximum:", df["lor"].max())

LOR Range
Minimum: 1.0
Maximum: 5.0

In [58]:
print("CGPA Range")
print("Minimum:", df["cgpa"].min())
print("Maximum:", df["cgpa"].max())

CGPA Range
Minimum: 6.8
Maximum: 9.92

In [59]:
print("Research Experience Values:")
print(df["research"].unique())

Research Experience Values:
[1 0]

In [60]:
print("Chance of Admit Range")
print("Minimum:", df["chance_of_admit"].min())
print("Maximum:", df["chance_of_admit"].max())

Chance of Admit Range
Minimum: 0.34
Maximum: 0.97

In [61]:
print("GRE outside range:",
      ((df["gre_score"] < 290) | (df["gre_score"] > 340)).sum())

print("TOEFL outside range:",
      ((df["toefl_score"] < 92) | (df["toefl_score"] > 120)).sum())

print("University Rating outside range:",
      ((df["university_rating"] < 1) | (df["university_rating"] > 5)).sum())

print("SOP outside range:",
      ((df["sop"] < 1) | (df["sop"] > 5)).sum())

print("LOR outside range:",
      ((df["lor"] < 1) | (df["lor"] > 5)).sum())

print("CGPA outside range:",
      ((df["cgpa"] < 6.8) | (df["cgpa"] > 9.92)).sum())

print("Research outside range:",
      (~df["research"].isin([0, 1])).sum())

print("Chance of Admit outside range:",
      ((df["chance_of_admit"] < 0.34) |
       (df["chance_of_admit"] > 0.97)).sum())

GRE outside range: 0
TOEFL outside range: 0
University Rating outside range: 0
SOP outside range: 0
LOR outside range: 0
CGPA outside range: 0
Research outside range: 0
Chance of Admit outside range: 0

## Day 7 Conclusion

The dataset was checked for valid ranges. GRE Score, TOEFL Score,
University Rating, SOP, LOR, CGPA, Research Experience, and Chance of
Admit were checked. No invalid values were found outside the expected
ranges.

In [63]:
print("Day 7 completed successfully!")
print("Total rows:", len(df))
print("Total columns:", len(df.columns))
print("Dataset shape:", df.shape)

Day 7 completed successfully!
Total rows: 400
Total columns: 9
Dataset shape: (400, 9)